# Generated by Django 4.0.6 on 2022-07-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_remove_answer_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(to='survey.answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
