# Generated by Django 4.0.6 on 2022-08-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_remove_useranswer_answer_remove_useranswer_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='responses',
            field=models.ManyToManyField(to='survey.userresponse'),
        ),
    ]
