# Generated by Django 4.0.6 on 2022-07-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_response'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='ResponseObject',
        ),
    ]
