# Generated by Django 4.0.6 on 2022-08-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_userresponse_question_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='responses',
            field=models.ManyToManyField(null=True, to='survey.userresponse'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='response',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
