# Generated by Django 4.0.6 on 2022-08-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_alter_question_responses_alter_userresponse_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.survey'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='response',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
