# Generated by Django 4.0.6 on 2022-08-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_userresponse_survey_alter_userresponse_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.IntegerField()),
                ('question_2', models.IntegerField()),
                ('question_3', models.IntegerField()),
                ('question_4', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='response',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='user_responses',
            field=models.ManyToManyField(to='survey.question'),
        ),
    ]
