# Generated by Django 4.0.6 on 2022-08-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_question_remove_userresponse_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='user_responses',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='user_responses',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.question'),
        ),
    ]
