# Generated by Django 4.0.6 on 2022-08-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_remove_userresponse_user_responses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='survey',
        ),
        migrations.AddField(
            model_name='question',
            name='question_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_4',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
